host: 0.0.0.0

#page title
page_title                                : Frame Grabber                             # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1434703541                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/frame-grabber/id1434703541 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon-v1.3.1.png                   # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually. When chaning, use new filename for cache busting.
app_name                                  : Frame Grabber                             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Capture amazing video moments.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Arthur Hammer
your_link                                 : https://arthurhammer.de
your_city                                 : Germany ❤️
email_address                             : hi@arthurhammer.de
facebook_username                         :
instagram_username                        : ar.hammer
twitter_username                          :
github_username                           : arthurhammer
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : From Video to Photo
    description                           : From snowboard tricks to selfie videos to bird watching. Grab and share the coolest frames in your videos!
    fontawesome_icon_name                 : photo-video

  - title                                 : Highest Quality
    description                           : Export frames in full resolution whether it be 4K, 5K or 8K. Never take a screenshot again.
    fontawesome_icon_name                 : star

  - title                                 : Precise Controls
    description                           : Compare frame by frame and zoom in for all details to find the exact moment you want.
    fontawesome_icon_name                 : expand

  - title                                 : Works Anywhere
    description                           : Use your photo library, import from Files or record videos. Even works with Live Photos.
    fontawesome_icon_name                 : bolt

  - title                                 : Fine-tune the Results
    description                           : Control the image format and quality. Review and attach Exif metadata.
    fontawesome_icon_name                 : toggle-on

  - title                                 : Privacy
    description                           : No ads, no tracking, no funny stuff. Your data is yours.
    fontawesome_icon_name                 : thumbs-up


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage-v1.3.1.jpg                 # Replace with alternative image path or image URL. When chaning, use new filename for cache busting.
cover_overlay_color                       : "#4c69af"
cover_overlay_transparency                : 0.7

device_color                              :                                      # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#7747FD"
feature_icons_background_color            : "#7747FD15"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown